services:
  task_app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - kitchy_mysql
    volumes:
      - .:/app
      - /app/node_modules

  kitchy_mysql:
    image: mysql:8
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d

volumes:
  mysql-data:
